name: mkr_flutter
description: Fan made of MyKampus Radio mobile apps.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependency_overrides:
  path_provider: 2.1.5
  shared_preferences: 2.3.5
  sqflite: 2.4.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  just_audio: ^0.9.43
  just_audio_windows: ^0.2.2
  audio_service: ^0.18.16
  http: ^1.2.2
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.1
  adaptive_theme: ^3.7.0
  desktop_window: ^0.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - images/

msix_config:
  display_name: MKR Unofficial App
  publisher_display_name: saifymatteo
  identity_name: com.saifymatteo.mkr-flutter
  logo_path: images\launcher\mkr-launcher.png
  capabilities: internetClient
  languages: ms-my, en-us
